# Generated by Django 3.0.4 on 2020-03-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computergame',
            name='platform',
            field=models.ManyToManyField(to='catalog.Platform'),
        ),
    ]
