# Generated by Django 3.0.4 on 2020-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateField(verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='computergame',
            name='date',
            field=models.DateField(verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='date',
            field=models.DateField(verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='date',
            field=models.DateField(verbose_name='дата создания'),
        ),
    ]
