# Generated by Django 3.0.4 on 2020-03-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='company',
            name='game',
        ),
        migrations.RemoveField(
            model_name='company',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='game',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='game',
        ),
        migrations.AddField(
            model_name='computergame',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Company'),
        ),
        migrations.AddField(
            model_name='computergame',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Engine'),
        ),
        migrations.AddField(
            model_name='computergame',
            name='platform',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Platform'),
        ),
        migrations.AddField(
            model_name='engine',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Company'),
        ),
        migrations.AddField(
            model_name='platform',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Company'),
        ),
    ]
