# Generated by Django 3.0.4 on 2020-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200322_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computergame',
            name='platform',
            field=models.ManyToManyField(to='catalog.Platform'),
        ),
    ]
