# Generated by Django 3.0.4 on 2020-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200318_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='date',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='date',
        ),
        migrations.AlterField(
            model_name='company',
            name='place',
            field=models.CharField(max_length=50, verbose_name='место расположения'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='language',
            field=models.CharField(max_length=50, verbose_name='язык программирования'),
        ),
    ]
